### ISSUE TITLE
Node  returns nothing - log shows an UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by juggledad** [RedBackSpider/node-red-contrib-pdfjs#2]
OS: macOS v10.14.6
Node-RED version: v1.1.3
Node.js  version: v12.13.0

Flow: `inject`->`pdfjs`->`inject` path to pdf file hard coded in the node. In Node-RED nothing shows up even with a `catch` node on the page.

In the console log I see:

> 25 Aug 07:30:02 - [info] Started modified flows
> (node:96628) UnhandledPromiseRejectionWarning: ReferenceError: ReadableStream is not defined
>     at MessageHandler.sendWithStream (/Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:45460:5)
>     at new PDFWorkerStreamReader (/Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:45833:45)
>     at PDFWorkerStream.getFullReader (/Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:45797:31)
>     at getPdfManager (/Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:306:35)
>     at setupDoc (/Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:457:7)
>     at wphReady (/Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:646:7)
>     at LoopbackPort.MessageHandler._onComObjOnMessage (/Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:45410:7)
>     at /Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.js:2062:18
>     at Array.forEach (<anonymous>)
>     at /Users/Paul/.node-red/node_modules/pdfjs-dist/build/pdf.js:2061:23
>     at runNextTicks (internal/process/task_queues.js:58:5)
>     at processImmediate (internal/timers.js:412:9)
> (node:96628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
>

**Comment by juggledad** [comment]
Also get the same error on a raspberry pi:

> 25 Aug 08:14:00 - [info] Started modified flows
> (node:20658) UnhandledPromiseRejectionWarning: ReferenceError: ReadableStream is not defined
>     at MessageHandler.sendWithStream (/home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:45460:5)
>     at new PDFWorkerStreamReader (/home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:45833:45)
>     at PDFWorkerStream.getFullReader (/home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:45797:31)
>     at getPdfManager (/home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:306:35)
>     at setupDoc (/home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:457:7)
>     at wphReady (/home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:646:7)
>     at LoopbackPort.MessageHandler._onComObjOnMessage (/home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.worker.js:45410:7)
>     at /home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.js:2062:18
>     at Array.forEach (<anonymous>)
>     at /home/pi/.node-red/node_modules/pdfjs-dist/build/pdf.js:2061:23
> (node:20658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:20658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>
